### ISSUE TITLE
Convert Object to dict

### ISSUE THREAD

**Issue by eddsalkield** [calmjs/calmjs.parse#35]
Firstly, thanks so much for your work on this project!  It's really great.

I'm writing a scraper that extracts some javascript from a web page, and walks over it using `calmjs.parse` to extract some information from an Object into a dict.

I could just write my own recursive converter over Objects, but if I were to submit a PR that extends the `calmjs.parse.asttypes.Object` class with a `dict` method that returns a dict representation of the Object, would you be willing to merge it?

I'm open to other ways of implementing this object to dict function, but this was my first idea.

**Comment by metatoaster** [comment]
Thank you for your interest and your use of this package, your thanks is much appreciated.

I had to gather my thought about this (revisiting this project since I haven't had the time to touch this project), and my conclusion is that I would not merge this in as proposed, simply because the core design actually decouples the `__repr__` and `__str__` representation from the underlying [`asttypes.Node`](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/asttypes.py#L38..L149) class.  Instead, a [factory class](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/factory.py#L14..L49) was used to produce the final `asttype.Node` classes that are then used by individual parsers for each ECMAScript version, as the composition model avoids the rigidity of class inheritance (given that inheritance is already being used for specific asttypes; adding another layer of "inheritance" on top would be overbearing), thus resulting in a common, foundation `Node` asttype which may easily be reused for each implemented ECMAScript versions supported by this library.

Moreover, as the proposal would require changing the `__iter__` for `asttypes.Object` nodes to _guarantee_ yielding of a series of 2-tuples such that the result can be mapped to a `dict` with the "expected" values, it may require a complete change to the original "visitor" (which I call a walker in `calmjs.parse`) API to adapt to this new `__iter__` method as it may no longer yield individual inner node instances of `asttypes.Node` subclasses as per the [current implementation](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/asttypes.py#L139..L142).  This is too much of an invasive change required for a successful implement of "`dict` castable" asttypes.Object instances to not directly impact the current expected use.

However, this is not to say what you want isn't exactly "impossible" under the current implementation, here's a simple demonstration:

```pycon
>>> from calmjs.parse import es5
>>> from calmjs.parse import es5
>>> tree = es5('s = {"a": "1", "b": "2"}')
>>> tree.children()[0].expr.right
<Object @1:5 properties=[
  <Assign @1:9 left=<String @1:6 value='"a"'>, op=':', right=<String @1:11 value='"1"'>>,
  <Assign @1:19 left=<String @1:16 value='"b"'>, op=':', right=<String @1:21 value='"2"'>>
]>
```

To start things off, the above is a simple piece of code that creates a simple JavaScript object assignment to a variable called `s`, and then that particular node may be directly accessed using `tree.children()[0].expr.right` (may be queried using the [tree walking method](https://github.com/calmjs/calmjs.parse#tree-walking) as outlined in the linked section on the readme), and let's see what happens when that gets "casted" to a `dict`:

```pycon
>>> dict(tree.children()[0].expr.right)
{<String @1:6 value='"a"'>: <String @1:11 value='"1"'>, <String @1:16 value='"b"'>: <String @1:21 value='"2"'>}
```

Ah ha! So it does work somewhat! Though do note that this simply is the result of the side-effect of individual `asttypes.Assign` nodes (with the `:` operator) yielding exactly two nodes - left and right (which gets interpreted as a 2-tuple by `dict`).  However, as you will note, the resulting `dict` is constructed using the original `asttypes.String` instances and won't be actual strings (or other base datatypes e.g. `int`), as this will require overriding the `__iter__` implementation to specifically `yield` the underlying type.  Now do note that keys for JavaScript objects may be provided as "unquoted" strings:

```pycon
>>> tree = es5('s = {a: "1", b: "2"}')
>>> dict(tree.children()[0].expr.right)
{<PropIdentifier @1:6 value='a'>: <String @1:9 value='"1"'>, <PropIdentifier @1:14 value='b'>: <String @1:17 value='"2"'>}
```

Note that the keys are no longer instances of the `String` class but of `PropIdentifier` class, so they may need to be dealt with differently (e.g. they don't have the quotes that will required to be stripped out after casted to a `str`) when further conversion is required (e.g. for use with `json.dumps`).  This can actually be side-stepped using dictionary comprehension to cast the key to a `str` as a quick and naive way (see next example).

Our example will completely break down if we have nested objects, or list item as values:

```pycon
>>> tree = es5('s = {nested: {"ab": 12, "cd": 34}, items: [1, 2, 3]}')
>>> # do the naive casting in a dict comprension
>>> mapping = dict({str(i): j for i, j in tree.children()[0].expr.right})
>>> mapping['items']
<Array @1:43 items=[
  <Number @1:44 value='1'>,
  <Number @1:47 value='2'>,
  <Number @1:50 value='3'>
]>
>>> mapping['nested']
<Object @1:14 properties=[
  <Assign @1:19 left=<String @1:15 value='"ab"'>, op=':', right=<Number @1:21 value='12'>>,
  <Assign @1:29 left=<String @1:25 value='"cd"'>, op=':', right=<Number @1:31 value='34'>>
]>
```

(Note the naive cast to `str` only works here because all the keys are of the `PropIdentifier` type; other asttypes may not provide the expected results using the example dict comprehension.)

As the `dict` type constructor has no concept beyond turning a series of 2-tuple into a key: value pair, any value of specific types will be returned as-is and will not give the user the expected result. Since the `items` value is simply an opaque `Array` object and not the underlying Python list and that the `nested` value is again another Object, this should lead to the intuition that a real solution must recursively turn the `Object` nodes into `dict`, which `dict` by itself will not do. Moreover, this shows clearly that individual types need to be dealt with so they will naturally turn into the expected underlying Python base types (e.g. `list`, `str`, `int`).

Not to mention that there is no handling for identifiers: do raw variables simply be casted to a raw string, or should that be dereferenced an assigned value accessible in the corresponding scope within the code somewhere, for example:

```pycon
>>> tree = es5("""
... number = 1
... obj = {"a": number}
... """)
>>> dict(tree.children()[1].expr.right)
{<String @3:8 value='"a"'>: <Identifier @3:13 value='number'>}
```

Clearly that may not be what the user expects.  Hence I will not support this implementation or use case in the core `calmjs.parse` library, as it will inevitably give false expectations as to what this may or may not do.  The work to solve this is non trivial, but certainly these are problems which may be addressed, and my suggestion is definitely implement this as some kind of walker that will produce the expected output per each individual use case, and maybe if one such implementation that may be adaptable and sufficiently generic enough with maximized reusability, I may be inclined to have that be included.  It really should be a robust API and the above examples are just some limitations that need to be overcome, to not mislead users into using something not fit for purpose.

If I were to implement this, I certainly will follow [a composed definition](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/unparsers/es5.py#L57) with newly implemented handlers for each specific types, such that it may be plugged into the [standard unparser](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/unparsers/base.py#L22) such that replacement routine (e.g. for dealing with variables or specific node types) may be handled in a reusable pattern, but I will agree that this requires deep understanding of this implementation, so a walker, while more rigid and specific, is probably the preferred approach (as the existing handlers may be leveraged to be extended to handle the variable dereferencing problem; one base candidate would be the [Scope tracker](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/handlers/obfuscation.py#L67) used by the [Obfuscator](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/handlers/obfuscation.py#L363) class that underlies the [minify printer](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/unparsers/es5.py#L410..L445)).

If you want to tackle this in the least invasive manner (as I think it would be onerous and overbearingly unreasonable to force every potential contributor to understand the whole unparsing framework in this library), I think providing some example code on a basic framework to produce a desired output using the [basic walker](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/walkers.py#L12) might be a good starting point, as that may be included in the README file as a starting piece of documentation before leading to any kind of library inclusion.

**Comment by eddsalkield** [comment]
Thanks for such a comprehensive response!

On reflection, I agree that having a method on the AST itself is a bad idea.  Defining a walker over the AST seems to make a lot more sense.  I've had a crack at an initial implementation; I'll describe my approach and link you to a gist.

I've noticed that the current `Walker` isn't generic enough to let you tail-recursively evaluate the AST like we want, since it just provides a generator of nodes.  Therefore I implemented a more generic `Visitor[T]` class for some polymorphic type `T`.  `Visitor[T]` exposes a `visit` method that operates on a node, and dispatches a method to handle the visitation, returning an object of type `T`.  The method that is dispatched is determined according to its `_visit_dispatch` data structure.

`_visit_dispatch` is a dict attribute of `Visitor[T]` that maps filtering functions to methods of type `Node -> T`.  `Visitor[T].visit` determines which method to dispatch by evaluating `node` against each key in `_visit_dispatch`.  If the evaluation is successful, then the corresponding dict value method is dispatched.  If there are no matches, the `generic_dispatch` method is run.

Subclasses of `Visitor[T]` can be defined to include additional methods within `_visit_dispatch` by decorating those methods with `mark_visitor`.  The argument of `mark_visitor` is the filtering function to apply.

Next, we define a `Transformer`, which is the base class for visitors that transform the AST.  Essentially it's a `Visitor[Node]`.  It is currently unimplemented, but it will eventually implement `visit_generic` to return a cloned version of the node, having mapped a function over all of its children.  This is currently hard to implement because there's no standard interface for setting children within a node.  I noticed that there was willingness to do this anyway from [this code comment](https://github.com/calmjs/calmjs.parse/blob/4e9cef7e15a152b7ce2d5a79ada87b05a25fc39f/src/calmjs/parse/asttypes.py#L144).  I'd like to know if you're still willing to consider such an interface.

Finally, we can define the classes that actually do the conversion.  I define `JSONify` that is a `Visitor[JSON]`.  It adds additional visitor methods to recursively handle objects, arrays and literals.  It fails on everything else.

To make this more robust, I define `ConstantFolder`, that is a `Transformer` (therefore it's a `Visitor[Node]`).  It recursively iterates over the tree looking for unary and binary operators, and where possible folds them into literals.

The `Visitor[T]` is more generic than the current `Walker`, and so I've provided a draft implementation of the `Walker` as a `Visitor[Generator[Node, None, None]]`.  In essence, it's a `Visitor` that, for a given node, returns a Generator of nodes.  Filtering is achieved through a `visit_filter` method that gets dispatched when the filter condition is satisfied.

Although the interface of `Walker` in my draft is currently different to the current one in `calmjs.parser`, it is of course possible to make it backwards-compatible.

You can take a look at the code sketch here: https://gist.github.com/eddsalkield/4be498a6141e3cb3ae96c239b3149deb

Please note that it's currently incomplete, and almost certainly contains bugs.  There are also a handful of minor questions in code comments that I'd appreciate you looking at.

**Comment by metatoaster** [comment]
Hi again.  Upon thinking about this some more, I think it might actually be even more beneficial to have your package as a separate library, almost.  I am not saying I would reject your contribution (e.g. if you have specific requirements/bug fixes needed to `calmjs.parse` in order for your code to work that isn't going to change the API, that is definitely welcomed). I am actually saying that you got some very good ideas that require Python 3 specific features (namely using `typing` with type hinting) which I am not quite ready to incorporate fully into this library (unless a completely major version (i.e. `calmjs.parse-2.0.0`) is done for Python 3 happens, since I have maintained Python 2.7 support as there may still be other users out there somewhere needing this).  I must also admit that I still have projects that I maintain that is stuck in 2.7 (due to lack of time/interests in doing the Python 3 migration) that I am unwilling to drop this requirement for this package.

Another thing I am also thinking about is also querying for objects inside the AST.  Navigation can be cumbersome through the current walker implementations (the [generic one](https://github.com/calmjs/calmjs.parse/blob/master/src/calmjs/parse/walkers.py) and the one [for unparsing](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/unparsers/walker.py).  This definitely would be better fit in a separate package possibly.

Also, your approach seem to be a variation of the definition table I have, albeit in a more generic manner but done in a way tightly coupled to class definitions. I avoided that approach for the reason I explained previously (and that it encourages the "visitor" pattern which Python can only really emulate as it doesn't function in the same way as Java does, so I opted to avoid this misnomer by calling them "walkers" (tree walking) and "handlers" (for a specific type) - not a huge deal, it's my personal preference that got reflected in the resulting library).  So I think that's something that can be welcomed.

That said, I am unable to get your code to work right off the bat (which I think that's what you meant by this being a code sketch and being incomplete).  I tried fixing some errors, so roughly the following are my remarks (I tested using Python 3.8; don't currently have 3.9 installed):

- First argument of [`typing.Callable`](https://docs.python.org/3/library/typing.html#callable) requires a `list`, so the signature for the visit functions should probably be `[Callable[[ast.Node], bool]]` (I would link the diff, but right now gist's direct anchor link to diff is broken (it is reusing the same diff id for some reason), so [the full file is linked](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/299fa2cfda34bdda023191d1856f58edb4d46367#file-dict_walker-py-L9,L19); you will have to scroll down to find the diff in the [full revision](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/revisions#)).
- The `isinstance` function does not work against `typing.Union`. Related threads [here](https://stackoverflow.com/questions/56493140/parameterized-generics-cannot-be-used-with-class-or-instance-checks), [here](https://stackoverflow.com/questions/42027923/mypy-differences-in-isinstance-and-issubclass-from-python-3-5-to-3-6-in-paramete) and [here](https://stackoverflow.com/questions/51171908/extracting-data-from-typing-types). My experience so far with type hinting and the whole `typing` module in Python has been extremely clouded by issues like these, so if I really want to write programs with a strong type system and guarantees that are sound, I would eschew the use of Python (which I have done, I am in fact moving my main development language to Rust, as an aside, I really don't care for dealing with strict type checking in Python because the core of the ecosystem surrounding the language was not robustly designed as such, thus not fit for purpose; if I have to deal with the clutter introduced by all these type annotations that do not work, I'd rather not have them, or migrate to a language that will correctly type-check against these in a way that actually works, which Rust does). ([code](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/568d28ef08ae0750b6ce2424113a5a6eb06a36b6#file-dict_walker-py-L100))
- The `mark_visitor` doesn't actually return a wrapped callable that has the `should_visit` attribute set, and that the original function actually got dropped completely since [parameterized decorators](https://stackoverflow.com/questions/5929107/decorators-with-parameters) have to return a prepared decorator that would actually returned the wrapped function. ([code](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/0ab0943cfcf624f3113bc5fc01efaa7ddfa34900#file-dict_walker-py-L9..L15))
- However, doing so somehow mess with how Python binds functions as methods to a class, as the returned wrapper will be somehow stripped of the context of the class and will become a standard function, thus `self` will not be implicitly passed to `visit` in the `Dispatcher` section (in the `visit(self, node: ast.Node) -> T:` method).

   ```pycon
   >>> jsonify.visit(tree.children()[0].expr.right)
   Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/tmp/54006fb9d410d3859d2ca1bdf18e7b74/dict_walker.py", line 50, in visit
       return visitor(node)
     File "/tmp/54006fb9d410d3859d2ca1bdf18e7b74/dict_walker.py", line 12, in wrapper
       return f(*a, **kw)
   TypeError: visit_object() missing 1 required positional argument: 'node'
   ```

  For this reason (and various others; this is only but a minor one) I completely decoupled all "visitor methods" from classes as I may have tried your exact approach years ago (for a different project) and I just learned to compose things by lookup tables and define really simple/small objects focused on tracking attributes for tasks like these. So the way I see it is that your implementation is an even more generic version of my walker-dispatcher pattern, albeit coupled to a class (which is where this differ). ([code](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/c10844d9949a5cd14e9be22d8e1ad6341f16b025#file-dict_walker-py-L50))

Now, with the [main](https://gist.github.com/metatoaster/54006fb9d410d3859d2ca1bdf18e7b74/8136025fca53510b5339ed575e51feab7f52c4be#file-dict_walker-py-L175..L179) stub added as an example, we finally see that your code does achieve producing the following:

```console
$ python dict_walker.py 
{<PropIdentifier @1:6 value='a'>: '"b"'}
```

That's a first start.  Now you might recall why I wanted the dispatcher model.  My proposal under that framing would mean constructing something like the [definition](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/unparsers/es5.py#L57..L362) I linked previously would define how a dictionary walker may be constructed, using new tokens (which for the unparser, I put them in the [`ruletypes`](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/ruletypes.py) module).  Pretend all the tokens I have as the example below are implemented:

```python
definitions = {
    # "default" need to be navigate/omit
    'PropIdentifier': (Attr('value'),),
    # Must produce the 2-tuple
    'Assign': (AttrToDictKey('left'), AttrToDictValue('right'),),
    'Number': (AttrToNumber('value'),),
    'Boolean': (AttrToBool('value'),),
    'Null': (AttrToNone(),),
    'String': (Attr(Literal()),),
    # 'FuncDecl': (),
    # 'FuncExpr': (),
    'Regex': (AttrToStr('value'),),
    'FunctionCall': (),
    'Object': (AttrToDict('properties'),),
    'Array': (AttrToList('items'),),
    # 'Elision': (),
}
```

 Again, this is simply a continuation on what my approach on this might look like, based on the definition format I linked, to demonstrate an approach that is decoupled from Python classes, but instead done in a way that is composed based on the underlying class names. Anyway, if those tokens were implemented, the entire `definitions` would be fed into the dispatcher built in a way that would produce a valid `dict` (or `list`) from an input (much like how the current pretty printer does, but instead a `str` output, it would be a `dict` or whatever supported assignment values). Also this design would allow users who wish to extend this to simply define a standalone function not coupled to any class (no subclassing needed) and just compose a definition as such, so that if they want to pass functions to `node` to produce a valid value (no idea how they might achieve that), they can.

My envisioned result of this is a generalized variable extractor from a JavaScript input source, rather than constricting it to some specific `Object` node.  Meaning I can just throw in a source code, and pass the resulting tree into a callable that will produce something like this:

```pycon
>>> from calmjs.parse import es5
>>> tree = es5('''
... var mapping = {
...     foo: "bar",
...     lookup: {
...         baz: "ok",
...         "success": true, 
...     }, 
... };
... var t = 123; 
...  
... function something(a, b, c) {
...     var inner = [1, 2, 3]; 
...     // other code omitted 
... } 
... ''') 
>>> extracted = extractor(tree)
>>> extracted.t
123
>>> extracted.something.inner
[1, 2, 3]
>>> extracted.mapping['lookup']
{'baz': 'ok', 'success': True}
```

Again, this was in fact something I actually have been thinking of doing when I was more heavily involved with dealing with reasoning over JavaScript sources (when I was trying to come up with a way to deal with [finding Node.js imports (`require()`)](https://github.com/calmjs/calmjs.webpack/blob/master/src/calmjs/webpack/interrogation.py), in the context of trying to make webpack make sense for use in Python through Calmjs), so that's something I would actually find useful.

Anyway, I must also apologize for going off on another massive rant and tangent, but hopefully the code feedback I gave so far will be a good starting point for you.  I haven't fully read the comments in the code as I was focused on patching your example implementation into a form that would produce something, and due to timing issues I may have to revisit those comments another time.

**Comment by metatoaster** [comment]
I must admit this proposal of yours really nerdsniped me and ended up helping me find the bug that I missed (I definitely have saw it before but wasn't sure how to reproduce it; now I found it and it's now being dealt with via #36).  Anyway, I ended up building the definition and the various handlers/tokens needed to make it work, and you may take a look at it in my personal fork, or you may try the following:

```console
$ # if you already got a fork you may instead wish to add the appropriate remote and fetch the branch
$ git clone --branch var_extractor https://github.com/metatoaster/calmjs.parse.git
Cloning into 'calmjs.parse'...
...
$ cd calmjs.parse/
$ pip install -e .
Obtaining file:///tmp/calmjs.parse
...
$ python
```

From there:

```pycon
>>> from calmjs.parse import es5
>>> tree = es5('''
... s = {a: "b"}
... t = {
...     foo: 123.4,
...     "bar": true,
...     'baz': {
...         a: null,
...         b: [123, 456, 789.],
...     }
... }
... ''')
>>> from calmjs.parse.unparsers import extractor
>>> mapping = dict(extractor.build_dict(tree))
>>> mapping['t']
{'foo': '123.4', '"bar"': 'true', "'baz'": {'a': 'null', 'b': ['123', '456', '789.']}}
```

This is the first cut.  I am going to be adding the rest of the token types for dealing with nulls and numbers to provide the expected output, though I am seriously running out of time again and I am unlikely to deal with the cases for getting values inside function scopes and the like.

**Comment by eddsalkield** [comment]
Wow, count me impressed on this one!  It's taken me a few days to get around to reviewing this because there's a lot to unpack.

Firstly, I like the approach that you've implemented here; I completely agree that it's more robust and clean as compared to a visitor pattern, especially when we consider all the quirks that come along with Python's new type system.  It's nice that existing pieces, such as the `Dispatcher` and `BaseUnparser`, already exist and can be made use of.

That said, without first gaining deep knowledge of the internals of this library, it would have been really difficult for me to pull something like this off.  Therefore I wonder whether there's value in making the existing `Walker` more abstract anyway, to support future use cases that do more than iterate over each node.  Extending a class is quite natural to people thinking with a Pythonic mindset.  Either way, this is now pretty tangential to the data extraction discussion, maybe to be considered for a `calmjs.parse` 2.0.

I've thrown some random js files at this, and so far it all seems to be working well.  Checking that the result of the unparser on the `Object` node is of length 2 is a good idea; I think most people won't really care about nodes that therefore get skipped, like `GetPropAssign`, so skipping them is fine.  Certainly it's better than failing to cast to a `dict`.

Regarding a rewrite of `BinOp` and `UnaryExpr` operator handling, I imagine that we should give the end user choice over constant folding or string concatenation.  Would you be happy for two different sets of definitions to be provided, one for each use case?

Finally, regarding getting this into `master`, let's start a TODO list:

- [ ] Unit tests
- [ ] Mon/Binop constant folding

Anything else that comes to mind?

Once this is done, my next step will be in packaging this for Fedora.  Exciting times indeed.

**Comment by metatoaster** [comment]
> Wow, count me impressed on this one! It's taken me a few days to get around to reviewing this because there's a lot to unpack.
>
> Firstly, I like the approach that you've implemented here; I completely agree that it's more robust and clean as compared to a visitor pattern, especially when we consider all the quirks that come along with Python's new type system. It's nice that existing pieces, such as the Dispatcher and BaseUnparser, already exist and can be made use of.
>
> That said, without first gaining deep knowledge of the internals of this library, it would have been really difficult for me to pull something like this off. 

Yeah, that's why I did warn in my first reply that it does take quite a deep understanding, especially when I do think it's hampered by the lack of documentation and possibly my lack of diligence in searching/citing (if any) prior literature about similar algorithms. Also that I probably could have designed it in a more clear, concise and consistent manner, though my excuse for that was that I was under quite a bit of time pressure to get the library I was actually working on out the door, and this side quest was taking up much more time than I'd like by that point.

> Therefore I wonder whether there's value in making the existing Walker more abstract anyway, to support future use cases that do more than iterate over each node. Extending a class is quite natural to people thinking with a Pythonic mindset. Either way, this is now pretty tangential to the data extraction discussion, maybe to be considered for a calmjs.parse 2.0.

Possibly, however I think the walker pattern can simply be implemented by any downstream users in any way they like, they shouldn't feel obliged to subclass the provided demo walker class.  I might want to clear that up in the README.

In any case, what you have up with the TODO seems like a good summary. It might take me some time to make a new release with the new changes, since my current focus is completely elsewhere. That said, I must admit your eagerness has given me some motivation to wrap some of this up, though for the mean time I have created a feature tag based on what's been done so far, as an interim measure to make this installable.

```console
$ pip install git+https://github.com/calmjs/calmjs.parse.git@var_extractor_prototype#egg=calmjs.parse
Collecting calmjs.parse
  Cloning https://github.com/calmjs/calmjs.parse.git (to revision var_extractor_prototype) to /tmp/pip-install-0fdkz2wp/calmjs-parse_3025f4d67d6448b493d797b5c6e5c706
...
Successfully installed calmjs.parse-1.3.0.dev0
```

This only has the new untested class (due to complete lack of unit tests) and the additional changes do not seem to break any existing tests so everything else should function the same.   Hopefully I might have time over the course of this month to put a new release together with the features requested.

**Comment by metatoaster** [comment]
Forgot to note in the commit for #38 that it closes this issue.

Will be making a new release that will include this feature.  Please refer to the updated top level README for usage information.
