### ISSUE TITLE
Walk Tree Recursively

### ISSUE THREAD

**Issue by infosisio** [calmjs/calmjs.parse#37]
Hello,

Been playing a bit with the library.

Was wondering how could the tree be walked recursively? 

Thank you in advance.

**Comment by metatoaster** [comment]
Hi, the top level README [has a brief reference](https://github.com/calmjs/calmjs.parse#tree-walking) to one method of walking through the tree recursively using the `filter` method provided by the [`calmjs.parse.walkers.Walker`](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/walkers.py#L12..L106) class.  That is a basic default walker that has naive traversal.

Users are encouraged to write their own classes by either extending on this one or coming up with something on their own, as walkers are relatively trivial to implement, given that the most basic form can be done in basically two for loops.  The [`walk`](https://github.com/calmjs/calmjs.parse/blob/1.2.5/src/calmjs/parse/walkers.py#L64..L76) method can be done as a standalone function, and users can simply take that and extend it to do whatever they want to do.

**Comment by infosisio** [comment]
@metatoaster Thanks for the response. What I would like to find out, is there a quick way to only get top-level nodes? For instance, I would like to parse var assignments but start from them only when they are outside a function etc. If they are part of a function, I would like to visit them only when I start visiting the parent function, if that makes sense. Thanks again.

**Comment by metatoaster** [comment]
What you want to do may end up being rather cumbersome, simply due to the myriad of ways which ECMAScript ASTs can be structured (due to programs having a variety of structures and organizations and the flexibility of which ECMAScript lets programmers write). Let's take that filter method and make it a standalone function but without immediately yielding from the subchildren of the children of the input node, but instead have it always yield a generator that have the option to produce those nodes:

```pycon
>>> def filter(node, condition):
...     for child in node:
...         if condition(child):
...             yield child
...         yield (subchild for subchild in filter(child, condition))
```

Also reusing the source code from the tree walking declaration from the README to keep the example clean and naive:

```pycon
>>> from calmjs.parse import es5
>>> from calmjs.parse.asttypes import VarStatement
>>> declarations = es5(u'''
... var i = 1;  // 0th expression statement
... var s = {
...     a: "test",
...     o: {
...         v: "value"
...     }
... };
... foo({foo: "bar"});
... function bar() {  // 3rd expression statement
...     var t = {
...         foo: "bar",
...     };
...     return t;
... }
... foo.bar = bar;
... foo.bar();
... ''')
```

Let's see what happens when we use that filter function

```pycon
>>> for node in filter(declarations, lambda node: isinstance(node, VarStatement)):
...     print(node)
var i = 1;
<generator object filter.<locals>.<genexpr> at 0x7fc79ed732d0>
var s = {
  a: "test",
  o: {
    v: "value"
  }
};
<generator object filter.<locals>.<genexpr> at 0x7fc79ed732d0>
<generator object filter.<locals>.<genexpr> at 0x7fc79ed73350>
<generator object filter.<locals>.<genexpr> at 0x7fc79ed734d0>
<generator object filter.<locals>.<genexpr> at 0x7fc79ed733d0>
<generator object filter.<locals>.<genexpr> at 0x7fc79ed732d0>
```

So it does work, and the filter function will yield the generators that can be iterated through later should you wish to, but you will have to do them one at a time which may become cumbersome.  Rather than printing them out, let's just cast that to a list and assign it to a variable:

```pycon
>>> results = list(filter(declarations, lambda node: isinstance(node, VarStatement)))
>>> results[0]
<VarStatement @2:1 ?children=[
  <VarDecl @2:5 identifier=<Identifier @2:5 value='i'>, initializer=<Number @2:9 value='1'>>
]>
>>> print(results[2])
var s = {
  a: "test",
  o: {
    v: "value"
  }
};
```

So those are the `var` statements in the original source, and they are being interspersed by the additional generator that their own children may yield additional statements (though the implementation could simply put that in `else`, but you see, this is a very generic implementation that tries to yield as many things as possible, rather than as few, as the `condition` argument may be anything which lead to children nodes that `yield` a node may have subchildren that `yield` additional nodes) [1].  Through that we can determine that the 5th element in the `results` list should corresponding to the `function bar` definition (since it is the 3rd statement in the program, with the 0th and 1st statement yielding both a node and a generator; basically, the user will have to figure out which generator that were captured in that list will get them the desired results), so let's iterate through that

```pycon
>>> bar_function = list(results[5])
>>> bar
[<generator object filter.<locals>.<genexpr> at 0x7fc79ed73cd0>, <VarStatement @11:5 ?children=[
  <VarDecl @11:9 identifier=<Identifier @11:9 value='t'>, initializer=<Object @11:13 properties=[
    <Assign ...>
  ]>>
]>, <generator object filter.<locals>.<genexpr> at 0x7fc79ed73ed0>, <generator object filter.<locals>.<genexpr> at 0x7fc79ed73f50>]
>>> print(bar[1])
var t = {
  foo: "bar"
};
```

As you can see, doing it this way is much more cumbersome, making it almost no different to just simply navigating the source file:

```pycon
>>> print(declarations.children()[3].children()[1])
var t = {
  foo: "bar"
};
```

To get that specific assignment.  Hence there is simply no easy way to provide a "generic" walker that will cater to very specific use cases, because the base library (i.e. `calmjs.parse`) has no idea how their end users might provide source trees or to set up the infinite many ways which infinite many source trees may be traversed.  So my recommendation to you is that you experiment to your hearts desire to build your ideal traversal function specific to your very specific use case, because only you know what exactly you want (see point [1] noted earlier).

Again, the point I am trying to make is: just take the basic walk method/function as the skeleton function and put what you want in so that you will get the answer that you want with the input(s) you have.

I am going to close this issue assuming this extensive answer is more than enough to get you started, but should you have more specific questions beyond generic designs (e.g. I am okay with questions about specific internals that you might be unclear about direct usage of `calmjs.parse`, though I think I have given you everything you need to know about traversing the AST nodes since it's literally calling `for child_node in node` and do work on/with whatever `child_node` is; I am rather ambivalent towards questions that are more about your uncertainty with your goals and requirements as I have no way of knowing exactly what they are), you may continue your response in this thread.
