### ISSUE TITLE
WARNING: There are 3 unused tokens

### ISSUE THREAD

**Issue by prrvchr** [calmjs/calmjs.parse#42]
Hi,

I use calmjs, and when importing the package I have the following message:

```
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: There are 3 unused tokens
```

Is it possible not to have these messages?

Thanks

**Comment by metatoaster** [comment]
As documented in the [manual optimization](https://github.com/calmjs/calmjs.parse#manual-optimization) section of the documentation, these messages may be safely ignored.  However, you have indicated these messages show up upon import, this indicates that the installation method/source that you've got this package do not have this optimization done, can you please let me know how you've installed this package and where this was installed from?  For the mean time, just follow the manual optimization step and those warnings should no longer appear upon module import.

**Comment by metatoaster** [comment]
In any case, this was a reminder for me to complete #41 so that third-party packages are less likely to make the mistake of not including this pre-generated module in the releases they make by ensuring the optimization step is correctly issued upon building of this package from source.

This should be fully fixed when that pull request is merged.

**Comment by prrvchr** [comment]
Hi,
It's probably my way of installing the package that's causing the problem.

I use calmjs in a LibreOffice extension ([OAuth2OOo](https://github.com/prrvchr/OAuth2OOo)) written in python.
Depending on the version of LibreOffice under which I install this extension, the version of python is 3.8 with Windows (python is delivered with LibreOffice) or is taken from the system under Linux (generally it is version 3.10, but this can vary)
the calmjs package is integrated into the extension archive in a [folder](https://github.com/prrvchr/OAuth2OOo/tree/master/source/OAuth2OOo/service/pythonpath) which is added to the pythonpath by LibreOffice.
It come from the calmjs-3.4.4-py2.py3-none-any.whl zip archive but without optimization done...

Am I able to optimize the calmjs module if I don't yet know the python version?

**Comment by prrvchr** [comment]
`
python -m calmjs.parse.parsers.optimize
`

What folders and/or files are created, I only see two __pycache__ folders in calmjs/parse and calmjs/parse/parser after typing this command?

**Comment by metatoaster** [comment]
I noted the list of files that were in the wheel, they should go alongside the other modules under `calmjs/parse/parser`.

I unfortunately do not have the time nor resources to support non-standard package management.

**Comment by metatoaster** [comment]
> it's a shame that you didn't give me all the information to make this possible for calmjs.parse...

... but I already did mention you need to include those files in the list I've already provided in [this comment](https://github.com/calmjs/calmjs.parse/issues/42#issuecomment-1783716447) - just extract them from the `.whl` or the `.zip` file that you've downloaded or can [download again from PyPI](https://pypi.org/project/calmjs.parse/) and place them with the rest of the modules, how difficult is this to understand? Can you not see the filenames all include `py3`?  It's standard for all major Python versions (as in *all* Python 3, doesn't matter if 3.8 or 3.10), as implied by that comment, and documented in [this section](https://github.com/calmjs/calmjs.parse#manual-optimization) that I've linked before.

Please read _all_ the information that's already been presented rather than just accusing the person that already helped you with not giving you all the information.

**Comment by metatoaster** [comment]
In any case, `calmjs-1.3.1` is released with as much of the packaging aid I can give for all third-party software packagers; hopefully the included changes which include a relaxation of the requirement of the complete set of package metadata will be a sufficient workaround for your particular case, but as I noted before I don't officially support non-standard installations and python environments.

**Comment by prrvchr** [comment]
I just updated to `calmjs.parse 1.3.1` and it correctly generates the two tab files in `calmjs.parse.parsers` folder on first import of the `calmjs` module.

In fact on Windows I was missing the **pkg_resources** package which is necessary with **setuptools**, so the tab files were `unknown`.

Thank you for your help, I wouldn't have succeeded without you.

**Comment by prrvchr** [comment]
I think I got excited too quickly... I still get the messages when opening the extension in LibreOffice.

I don't really understand why, because the installation problem seems to be resolved. I have 2 files that are created in the `calmjs.parse.parsers` folder when installing the extension under LibreOffice:
- yacctab_es5_py3_ply3_11.py
- lextab_es5_py3_ply3_11.py

Well, in any case this doesn't seem to prevent `calmjs` from working...
